config/routes.rb
Rails.application.routes.draw do
	resources :insights

	root "insights#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/insight.rb
class Insight < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/insights_controller.rb
class InsightsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

	def index
		@insights = Insight.all.order("created_at DESC")
	end

	def new
		@insight = Insight.new
	end
		
	def create
		@insight = Insight.new(insight_params)

		if @insight.save
			redirect_to @insight, notice: "Sucessfully created new Insight"
		else
			render "new"
		end

	end

	def edit
	end

	def update
		if @insight.update(insight_params)
			redirect_to @insight, notice:"Insight sucessfully updated!"
		else
			render 'edit'	
		end
	end

	def destroy
		@insight.destroy
		redirect_to root_path
	end


	private 

	def insight_params
		params.require(:insight).permit(:title, :description)
	end

	def find_pin
		@insight = Insight.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/insights_helper.rb
module InsightsHelper
end

app/views/insights/_form.html.haml
= simple_form_for @insight, html: { multipart: true } do |f|
	- if @insight.errors.any?
		#errors
			%h2
				= pluralize(@insight.errors.count, "error")
				prevented this Insight from saving
			%ul
				- @insight.errors.full_messages.each do |msg|
					%li= msg

	/ .form-group
	/ 	= f.input :picture, input_html: { class: 'form-control' }

	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.input :description, input_html: { class: 'form-control' }

	= f.button :submit, class: "btn btn-primary"

app/views/insights/edit.html.haml
%h1 Edit Insight

= render 'form'

= link_to "Cancel", @insight

app/views/insights/index.html.haml
- @insights.each do |insight|
	%h2= link_to insight.title, insight

app/views/insights/new.html.haml
%h1 Send you Insight
= render 'form'

= link_to "Back", root_path

app/views/insights/show.html.haml
%h1= @insight.title
%p= @insight.description


= link_to "Back", root_path
= link_to "Edit", edit_insight_path
= link_to "Delete", insight_path, method: :delete, data: { confirm: "Are you sure?"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LadyClementina</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>